name = "Amb"
uuid = "c42f9944-9a8f-11e9-2851-1930a3e1c813"
authors = ["Shashi Gowda <shashigowda91@gmail.com>"]
version = "0.2.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1"
